"""Tests for sofer.codebook — multi-format analysis and markdown generation."""

import csv
import inspect
import sys
from pathlib import Path

import pytest

from sofer.codebook import (
    _build_markdown,
    _read_csv,
    _read_file,
    _read_jsonl,
    _read_parquet,
    _read_tsv,
    _read_xlsx,
    generate,
    generate_all,
    infer_column_type,
)

# ── infer_column_type ─────────────────────────────────────────────────────────

# The repository's configured default CSV dialect. ``generate`` and the
# ``_read_*`` readers take the dialect as **required** arguments (issue #260,
# rule 3), so each call passes it explicitly instead of a hardcoded default.
_DEFAULT_DELIMITER = ";"
_DEFAULT_ENCODING = "utf-8-sig"


class TestInferColumnTypeSamples:
    """Sample-value cases for the public infer_column_type (issue #162 migration)."""

    def test_numeric(self):
        assert infer_column_type(["1", "2", "3", "4"]) == "numeric"

    def test_numeric_with_decimals(self):
        assert infer_column_type(["1,5", "2,0", "3,7"]) == "numeric"

    def test_categorical(self):
        assert infer_column_type(["red", "blue", "green", "red"]) == "categorical/text"

    def test_mixed_mostly_numeric(self):
        vals = ["1", "2", "three", "4"]
        assert "mixed" in infer_column_type(vals)

    def test_empty_values(self):
        assert infer_column_type(["", "NA", "MISSING"]) == "categorical/text"

    def test_mixed_with_missing(self):
        vals = ["10", "", "20", "NA", "30"]
        # 3 numeric out of 5 → 0.6 → "mixed (mostly numeric)"
        assert "mixed" in infer_column_type(vals)

    def test_all_missing(self):
        assert infer_column_type(["NA", "NA", ""]) == "categorical/text"

    def test_single_value(self):
        assert infer_column_type(["42"]) == "numeric"
        assert infer_column_type(["hello"]) == "categorical/text"


class TestInferColumnType:
    """Public infer_column_type — API surface and representative expected outputs."""

    def test_public_api_exists(self):
        """infer_column_type should be importable and callable."""
        assert callable(infer_column_type)

    def test_representative_cases_expected_outputs(self):
        """Representative (values, expected) cases asserted directly on the live API."""
        assert infer_column_type(["1", "2", "3"]) == "numeric"
        assert infer_column_type(["red", "blue"]) == "categorical/text"
        assert infer_column_type(["1", "two", "3"]) == "mixed (mostly numeric)"
        assert infer_column_type(["NA", "", "MISSING"]) == "categorical/text"


# ── generate ──────────────────────────────────────────────────────────────────


class TestGenerate:
    def test_basic_codebook_structure(self, tmp_path):
        """Generated codebook should contain expected markdown sections."""
        csv_path = tmp_path / "test.csv"
        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            w = csv.writer(f, delimiter=";")
            w.writerow(["id", "name", "age"])
            w.writerow(["1", "Alice", "30"])
            w.writerow(["2", "Bob", "25"])

        result = generate(str(csv_path), delimiter=_DEFAULT_DELIMITER, encoding=_DEFAULT_ENCODING)

        assert "# Codebook: test.csv" in result
        assert "| # | Column" in result
        assert "`id`" in result
        assert "`name`" in result
        assert "`age`" in result
        assert "Generated by sofer" in result

    def test_codebook_with_missing_values(self, tmp_path):
        """Missing values should be reflected in the missing % column."""
        csv_path = tmp_path / "missing.csv"
        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            w = csv.writer(f, delimiter=";")
            w.writerow(["val"])
            w.writerow(["10"])
            w.writerow(["NA"])
            w.writerow([""])
            w.writerow(["30"])

        result = generate(
            str(csv_path), delimiter=_DEFAULT_DELIMITER, encoding=_DEFAULT_ENCODING, max_sample=10
        )
        # 2 out of 4 data rows are missing → 50%
        assert "50.0%" in result or "50%" in result

    def test_codebook_writes_to_file(self, tmp_path):
        """When output_path is given, the codebook should be written to disk."""
        csv_path = tmp_path / "data.csv"
        csv_path.write_text("x;y\n1;2\n", encoding="utf-8")
        out_path = tmp_path / "codebook.md"

        result = generate(
            str(csv_path),
            output_path=str(out_path),
            delimiter=_DEFAULT_DELIMITER,
            encoding=_DEFAULT_ENCODING,
        )
        assert out_path.exists()
        content = out_path.read_text(encoding="utf-8")
        assert "Codebook: data.csv" in content
        # Also returned as string
        assert result == content

    def test_codebook_row_count(self, tmp_path):
        """Row count should be accurate."""
        csv_path = tmp_path / "rows.csv"
        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            w = csv.writer(f, delimiter=";")
            w.writerow(["col"])
            for i in range(100):
                w.writerow([i])
        result = generate(
            str(csv_path),
            delimiter=_DEFAULT_DELIMITER,
            encoding=_DEFAULT_ENCODING,
            max_sample=1000,
        )
        assert "**Rows:** 100" in result

    def test_large_file_samples(self, tmp_path):
        """Files larger than max_sample should note they're sampled."""
        csv_path = tmp_path / "large.csv"
        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            w = csv.writer(f, delimiter=";")
            w.writerow(["x"])
            for i in range(5000):
                w.writerow([i])

        result = generate(
            str(csv_path),
            delimiter=_DEFAULT_DELIMITER,
            encoding=_DEFAULT_ENCODING,
            max_sample=100,
        )
        assert "sample" in result.lower()

    def test_small_file_is_full_scan(self, tmp_path):
        """Files smaller than max_sample should say 'full scan'."""
        csv_path = tmp_path / "small.csv"
        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            w = csv.writer(f, delimiter=";")
            w.writerow(["x"])
            for i in range(10):
                w.writerow([i])

        result = generate(
            str(csv_path),
            delimiter=_DEFAULT_DELIMITER,
            encoding=_DEFAULT_ENCODING,
            max_sample=100,
        )
        assert "full scan" in result.lower()

    def test_numeric_column_type_in_codebook(self, tmp_path):
        """A numeric column should be labelled 'numeric'."""
        csv_path = tmp_path / "nums.csv"
        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            w = csv.writer(f, delimiter=";")
            w.writerow(["value"])
            for i in range(20):
                w.writerow([i])

        result = generate(str(csv_path), delimiter=_DEFAULT_DELIMITER, encoding=_DEFAULT_ENCODING)
        assert "numeric" in result

    def test_categorical_column_type_in_codebook(self, tmp_path):
        """A text column should be labelled 'categorical/text'."""
        csv_path = tmp_path / "cats.csv"
        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            w = csv.writer(f, delimiter=";")
            w.writerow(["color"])
            for v in ["red", "blue", "green"] * 10:
                w.writerow([v])

        result = generate(str(csv_path), delimiter=_DEFAULT_DELIMITER, encoding=_DEFAULT_ENCODING)
        assert "categorical/text" in result


# ══════════════════════════════════════════════════════════════════════════════
#  Phase 4.1 — Unit tests for each _read_* reader
# ══════════════════════════════════════════════════════════════════════════════


class TestReadCsv:
    def test_reads_semicolon_delimited(self, tmp_path):
        csv_path = tmp_path / "data.csv"
        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            w = csv.writer(f, delimiter=";")
            w.writerow(["a", "b", "c"])
            w.writerow(["1", "x", "3"])
            w.writerow(["4", "y", "6"])

        headers, columns, dtypes = _read_csv(
            str(csv_path), delimiter=_DEFAULT_DELIMITER, encoding=_DEFAULT_ENCODING
        )

        assert headers == ["a", "b", "c"]
        assert dtypes is None
        assert columns == [["1", "4"], ["x", "y"], ["3", "6"]]

    def test_reads_comma_delimited(self, tmp_path):
        csv_path = tmp_path / "data.csv"
        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            w = csv.writer(f, delimiter=",")
            w.writerow(["x", "y"])
            w.writerow(["alpha", "beta"])

        headers, columns, _dtypes = _read_csv(
            str(csv_path), delimiter=",", encoding=_DEFAULT_ENCODING
        )

        assert headers == ["x", "y"]
        assert columns == [["alpha"], ["beta"]]

    def test_handles_uneven_rows(self, tmp_path):
        csv_path = tmp_path / "uneven.csv"
        csv_path.write_text("a;b;c\n1;2\n3\n", encoding="utf-8")

        headers, columns, _dtypes = _read_csv(
            str(csv_path), delimiter=_DEFAULT_DELIMITER, encoding=_DEFAULT_ENCODING
        )

        assert headers == ["a", "b", "c"]
        assert columns[0] == ["1", "3"]
        assert columns[1] == ["2", ""]
        assert columns[2] == ["", ""]

    def test_empty_file(self, tmp_path):
        csv_path = tmp_path / "empty.csv"
        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            w = csv.writer(f, delimiter=";")
            w.writerow(["only", "headers"])

        headers, columns, dtypes = _read_csv(
            str(csv_path), delimiter=_DEFAULT_DELIMITER, encoding=_DEFAULT_ENCODING
        )

        assert headers == ["only", "headers"]
        assert dtypes is None
        assert columns == [[], []]


class TestReadTsv:
    def test_reads_tab_delimited(self, tmp_path):
        tsv_path = tmp_path / "data.tsv"
        tsv_path.write_text("name\tage\nAlice\t30\nBob\t25\n", encoding="utf-8")

        headers, columns, dtypes = _read_tsv(str(tsv_path), encoding=_DEFAULT_ENCODING)

        assert headers == ["name", "age"]
        assert dtypes is None
        assert columns == [["Alice", "Bob"], ["30", "25"]]


class TestReadParquet:
    def test_reads_parquet_with_dtypes(self, tmp_path):
        import pyarrow as pa
        import pyarrow.parquet as pq

        pq_path = tmp_path / "data.parquet"
        table = pa.table(
            {
                "name": pa.array(["Alice", "Bob", "Charlie"]),
                "age": pa.array([30, 25, 35], type=pa.int64()),
                "active": pa.array([True, False, True]),
            }
        )
        pq.write_table(table, pq_path)

        headers, columns, dtypes = _read_parquet(str(pq_path))

        assert headers == ["name", "age", "active"]
        assert columns == [
            ["Alice", "Bob", "Charlie"],
            ["30", "25", "35"],
            ["True", "False", "True"],
        ]
        assert dtypes is not None
        assert dtypes["name"] == "string"
        assert "int" in dtypes["age"].lower()
        assert dtypes["active"] == "bool"

    def test_handles_null_values(self, tmp_path):
        import pyarrow as pa
        import pyarrow.parquet as pq

        pq_path = tmp_path / "nulls.parquet"
        table = pa.table({"x": pa.array(["a", None, "c"])})
        pq.write_table(table, pq_path)

        headers, columns, _dtypes = _read_parquet(str(pq_path))

        assert headers == ["x"]
        assert columns == [["a", "", "c"]]


class TestReadXlsx:
    def test_reads_xlsx_with_dtypes(self, tmp_path):
        import openpyxl

        xlsx_path = tmp_path / "data.xlsx"
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.append(["name", "score", "active"])
        ws.append(["Alice", 95, True])
        ws.append(["Bob", 82, False])
        wb.save(xlsx_path)

        headers, columns, dtypes = _read_xlsx(str(xlsx_path))

        assert headers == ["name", "score", "active"]
        assert columns == [["Alice", "Bob"], ["95", "82"], ["True", "False"]]
        assert dtypes is not None
        assert dtypes["name"] == "string"
        assert dtypes["score"] in ("int", "float")
        assert dtypes["active"] == "bool"

    def test_empty_xlsx(self, tmp_path):
        import openpyxl

        xlsx_path = tmp_path / "empty.xlsx"
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.append(["col_a", "col_b"])
        wb.save(xlsx_path)

        headers, columns, dtypes = _read_xlsx(str(xlsx_path))

        assert headers == ["col_a", "col_b"]
        assert columns == [[], []]
        assert dtypes == {"col_a": "unknown", "col_b": "unknown"}


class TestReadJsonl:
    def test_reads_jsonl(self, tmp_path):
        jsonl_path = tmp_path / "data.jsonl"
        jsonl_path.write_text(
            '{"name": "Alice", "age": 30}\n{"name": "Bob", "age": 25}\n',
            encoding="utf-8",
        )

        headers, columns, dtypes = _read_jsonl(str(jsonl_path))

        assert headers == ["name", "age"]
        assert dtypes is None
        assert columns == [["Alice", "Bob"], ["30", "25"]]

    def test_jsonl_missing_keys(self, tmp_path):
        jsonl_path = tmp_path / "partial.jsonl"
        jsonl_path.write_text(
            '{"a": 1, "b": 2}\n{"b": 3, "c": 4}\n',
            encoding="utf-8",
        )

        headers, columns, _dtypes = _read_jsonl(str(jsonl_path))

        assert headers == ["a", "b", "c"]
        assert columns[0] == ["1", ""]
        assert columns[1] == ["2", "3"]
        assert columns[2] == ["", "4"]

    def test_jsonl_empty_file(self, tmp_path):
        jsonl_path = tmp_path / "empty.jsonl"
        jsonl_path.write_text("", encoding="utf-8")

        headers, columns, dtypes = _read_jsonl(str(jsonl_path))

        assert headers == []
        assert columns == []
        assert dtypes is None


# ══════════════════════════════════════════════════════════════════════════════
#  Phase 4.2 — _read_file dispatcher tests
# ══════════════════════════════════════════════════════════════════════════════


class TestReadFileDispatcher:
    def test_routes_csv(self, tmp_path):
        p = tmp_path / "f.csv"
        p.write_text("a;b\n1;2\n", encoding="utf-8")
        headers, _columns, dtypes = _read_file(
            str(p), delimiter=_DEFAULT_DELIMITER, encoding=_DEFAULT_ENCODING
        )
        assert headers == ["a", "b"]
        assert dtypes is None

    def test_routes_tsv(self, tmp_path):
        p = tmp_path / "f.tsv"
        p.write_text("x\ty\n10\t20\n", encoding="utf-8")
        headers, _columns, _dtypes = _read_file(
            str(p), delimiter=_DEFAULT_DELIMITER, encoding=_DEFAULT_ENCODING
        )
        assert headers == ["x", "y"]

    def test_routes_parquet(self, tmp_path):
        import pyarrow as pa
        import pyarrow.parquet as pq

        p = tmp_path / "f.parquet"
        pq.write_table(pa.table({"v": [1]}), p)
        headers, _columns, dtypes = _read_file(
            str(p), delimiter=_DEFAULT_DELIMITER, encoding=_DEFAULT_ENCODING
        )
        assert headers == ["v"]
        assert dtypes is not None

    def test_routes_xlsx(self, tmp_path):
        import openpyxl

        p = tmp_path / "f.xlsx"
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.append(["k"])
        ws.append(["val"])
        wb.save(p)
        headers, _columns, dtypes = _read_file(
            str(p), delimiter=_DEFAULT_DELIMITER, encoding=_DEFAULT_ENCODING
        )
        assert headers == ["k"]
        assert dtypes is not None

    def test_routes_jsonl(self, tmp_path):
        p = tmp_path / "f.jsonl"
        p.write_text('{"q": "x"}\n', encoding="utf-8")
        headers, _columns, _dtypes = _read_file(
            str(p), delimiter=_DEFAULT_DELIMITER, encoding=_DEFAULT_ENCODING
        )
        assert headers == ["q"]

    def test_raises_unsupported(self, tmp_path):
        p = tmp_path / "f.txt"
        p.write_text("hello", encoding="utf-8")
        with pytest.raises(ValueError, match="Unsupported file format"):
            _read_file(str(p), delimiter=_DEFAULT_DELIMITER, encoding=_DEFAULT_ENCODING)


# ══════════════════════════════════════════════════════════════════════════════
#  Issue #260 — the dialect is a required argument, never a hardcoded default
# ══════════════════════════════════════════════════════════════════════════════


class TestDialectParametersAreRequired:
    """The readers and ``generate`` take the dialect as required arguments.

    Issue #260 / AGENTS.md rule 3: ``codebook.py`` must not carry a literal
    ``";"`` / ``"utf-8-sig"`` default that a caller can silently inherit. Each
    entry point fails closed when the dialect is omitted, and the value that is
    supplied is the one that drives parsing.
    """

    def test_generate_requires_delimiter_and_encoding(self, tmp_path):
        csv_path = tmp_path / "t.csv"
        csv_path.write_text("a;b\n1;2\n", encoding="utf-8")
        with pytest.raises(TypeError):
            generate(str(csv_path))

    def test_read_csv_requires_dialect(self, tmp_path):
        csv_path = tmp_path / "t.csv"
        csv_path.write_text("a;b\n1;2\n", encoding="utf-8")
        with pytest.raises(TypeError):
            _read_csv(str(csv_path))

    def test_read_tsv_requires_encoding(self, tmp_path):
        tsv_path = tmp_path / "t.tsv"
        tsv_path.write_text("a\tb\n1\t2\n", encoding="utf-8")
        with pytest.raises(TypeError):
            _read_tsv(str(tsv_path))

    def test_read_file_requires_dialect(self, tmp_path):
        csv_path = tmp_path / "t.csv"
        csv_path.write_text("a;b\n1;2\n", encoding="utf-8")
        with pytest.raises(TypeError):
            _read_file(str(csv_path))

    def test_supplied_dialect_drives_parsing(self, tmp_path):
        csv_path = tmp_path / "c.csv"
        csv_path.write_text("a,b\n1,2\n", encoding="utf-8")
        comma = generate(str(csv_path), delimiter=",", encoding=_DEFAULT_ENCODING)
        assert "`a`" in comma and "`b`" in comma
        semicolon = generate(str(csv_path), delimiter=";", encoding=_DEFAULT_ENCODING)
        assert "`a,b`" in semicolon

    def test_no_literal_dialect_default_in_signatures(self):
        """No literal dialect default survives in the four entry points."""
        for func in (generate, _read_csv, _read_tsv, _read_file):
            sig = inspect.signature(func)
            for name in ("delimiter", "encoding"):
                param = sig.parameters.get(name)
                if param is None:
                    continue
                assert param.default is inspect.Parameter.empty, (
                    f"{func.__name__}.{name} must not carry a literal default (issue #260, rule 3)"
                )


# ══════════════════════════════════════════════════════════════════════════════
#  Phase 4.3 — _build_markdown diff test
# ══════════════════════════════════════════════════════════════════════════════


class TestBuildMarkdown:
    def test_matches_generate_output(self, tmp_path):
        csv_path = tmp_path / "test.csv"
        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            w = csv.writer(f, delimiter=";")
            w.writerow(["id", "name", "age"])
            w.writerow(["1", "Alice", "30"])
            w.writerow(["2", "Bob", "25"])

        result_via_generate = generate(
            str(csv_path), delimiter=_DEFAULT_DELIMITER, encoding=_DEFAULT_ENCODING
        )

        headers, columns, dtypes = _read_file(
            str(csv_path), delimiter=_DEFAULT_DELIMITER, encoding=_DEFAULT_ENCODING
        )
        result_via_builder = _build_markdown(headers, columns, dtypes, str(csv_path))

        assert result_via_builder == result_via_generate

    def test_includes_actual_type_column(self):
        headers = ["name", "score"]
        columns = [["Alice", "Bob"], ["95", "82"]]
        dtypes = {"name": "string", "score": "int"}

        result = _build_markdown(headers, columns, dtypes, "data.csv")

        assert "| Actual Type |" in result
        assert "string" in result
        assert "int" in result

    def test_no_actual_type_when_dtypes_none(self):
        headers = ["col"]
        columns = [["a", "b"]]

        result = _build_markdown(headers, columns, None, "f.csv")

        assert "Actual Type" not in result

    def test_empty_file_minimal_codebook(self):
        headers = ["a", "b"]
        columns = [[], []]

        result = _build_markdown(headers, columns, None, "empty.csv")

        assert "# Codebook: empty.csv" in result
        assert "**Rows:** 0" in result
        assert "**Columns:** 2" in result

    def test_unique_counts_exclude_sentinels(self):
        """CB-R07 — the Unique cell counts distinct non-missing values only."""
        result = _build_markdown(
            headers=["val"],
            columns=[["A", "", "NA", "B", "NULL"]],
            dtypes=None,
            file_path="f.csv",
        )
        data_row = next(line for line in result.splitlines() if line.startswith("| 1 |"))
        cells = [c.strip() for c in data_row.split("|")]
        # cells: ['', '1', '`val`', type, unique, missing%, example, '']
        assert cells[4] == "2", f"expected unique=2 in row: {data_row}"

    def test_unique_counts_distinct_values(self):
        """Duplicate non-missing values collapse into one distinct value."""
        result = _build_markdown(
            headers=["val"],
            columns=[["x", "x", "y"]],
            dtypes=None,
            file_path="f.csv",
        )
        data_row = next(line for line in result.splitlines() if line.startswith("| 1 |"))
        cells = [c.strip() for c in data_row.split("|")]
        assert cells[4] == "2", f"expected unique=2 in row: {data_row}"


# ══════════════════════════════════════════════════════════════════════════════
#  Helper
# ══════════════════════════════════════════════════════════════════════════════


def _write_toml(base_path, entries):
    """Write a minimal dataset.toml with [[file]] entries to *base_path*."""
    lines = [
        "[dataset]",
        'name = "test-ds"',
        'repo_id = "user/test-ds"',
        "",
    ]
    for local in entries:
        lines.append("[[file]]")
        lines.append(f'local = "{local}"')
        lines.append(f'remote = "{local}"')
        lines.append("")

    toml_path = base_path / "dataset.toml"
    toml_path.write_text("\n".join(lines), encoding="utf-8")
    return toml_path


# ══════════════════════════════════════════════════════════════════════════════
#  Phase 4.4 — Integration tests for generate_all()
# ══════════════════════════════════════════════════════════════════════════════


class TestGenerateAll:
    def test_generates_for_all_toml_entries(self, tmp_path):
        from sofer.model import DatasetConfig

        a = tmp_path / "a.csv"
        a.write_text("x;y\n1;2\n", encoding="utf-8")
        b = tmp_path / "b.csv"
        b.write_text("p;q\n10;20\n", encoding="utf-8")

        toml_path = _write_toml(
            tmp_path,
            [
                str(a.relative_to(tmp_path)),
                str(b.relative_to(tmp_path)),
            ],
        )

        cfg = DatasetConfig.from_toml(toml_path)
        results = generate_all(cfg)

        codebooks_dir = tmp_path / "cache" / "codebooks"
        assert len(results) >= 3  # 2 per-file + root index
        assert (codebooks_dir / "a.md").exists()
        assert (codebooks_dir / "b.md").exists()
        root = tmp_path / "cache" / "codebook.md"
        assert root.exists()
        assert not (tmp_path / "codebook.md").exists()
        root_content = root.read_text(encoding="utf-8")
        assert "Codebook Index" in root_content
        assert "Tables:" in root_content

    def test_root_index_has_correct_links(self, tmp_path):
        from sofer.model import DatasetConfig

        sub = tmp_path / "cache"
        sub.mkdir()
        (sub / "f.csv").write_text("col\n1\n", encoding="utf-8")

        toml_path = _write_toml(tmp_path, ["cache/f.csv"])
        cfg = DatasetConfig.from_toml(toml_path)
        generate_all(cfg)

        root = tmp_path / "cache" / "codebook.md"
        assert root.exists()
        assert not (tmp_path / "codebook.md").exists()
        content = root.read_text(encoding="utf-8")
        # Root index links are relative to the artifact cache, not base_dir
        assert "[`codebooks/f.md`](codebooks/f.md)" in content
        assert "1 columns" in content

    def test_root_index_links_for_nested_subdirs(self, tmp_path):
        """Root index should use codebooks/ prefix for nested subdirectories."""
        from sofer.model import DatasetConfig

        sub = tmp_path / "cache" / "Labels"
        sub.mkdir(parents=True)
        (sub / "etiquetas_a.csv").write_text("k;v\n1;2\n", encoding="utf-8")

        toml_path = _write_toml(tmp_path, ["cache/Labels/etiquetas_a.csv"])
        cfg = DatasetConfig.from_toml(toml_path)
        generate_all(cfg)

        root = tmp_path / "cache" / "codebook.md"
        assert root.exists()
        assert not (tmp_path / "codebook.md").exists()
        content = root.read_text(encoding="utf-8")
        assert "[`codebooks/Labels/etiquetas_a.md`](codebooks/Labels/etiquetas_a.md)" in content

    def test_skips_unsupported_format(self, tmp_path, capsys):
        from sofer.model import DatasetConfig

        (tmp_path / "f.txt").write_text("hello", encoding="utf-8")

        toml_path = _write_toml(tmp_path, ["f.txt"])
        cfg = DatasetConfig.from_toml(toml_path)
        results = generate_all(cfg)

        assert results == []
        captured = capsys.readouterr()
        assert "Unsupported format" in captured.err

    def test_skips_missing_file(self, tmp_path, capsys):
        from sofer.model import DatasetConfig

        toml_path = _write_toml(tmp_path, ["nonexistent.csv"])
        cfg = DatasetConfig.from_toml(toml_path)
        results = generate_all(cfg)

        assert results == []
        captured = capsys.readouterr()
        assert "missing" in captured.err.lower()

    def test_skips_directory_entry(self, tmp_path, capsys):
        from sofer.model import DatasetConfig

        sub = tmp_path / "mydir"
        sub.mkdir()

        toml_path = _write_toml(tmp_path, ["mydir"])
        cfg = DatasetConfig.from_toml(toml_path)
        results = generate_all(cfg)

        assert results == []
        captured = capsys.readouterr()
        assert "directory" in captured.err.lower()


class TestGenerateAllOutputDir:
    """Option B (PRP-04): prepare writes codebooks directly into the output
    directory, never mutating the shared cache/codebooks/."""

    def _cfg_with(self, tmp_path, *rel_paths):
        from sofer.model import DatasetConfig

        for rel in rel_paths:
            local = tmp_path / rel
            local.parent.mkdir(parents=True, exist_ok=True)
            local.write_text("col;val\n1;2\n", encoding="utf-8")
        return DatasetConfig.from_toml(_write_toml(tmp_path, list(rel_paths)))

    def test_output_dir_receives_codebooks_and_root_index(self, tmp_path):
        """Codebooks land in output_dir/codebooks/ + output_dir/codebook.md;
        cache/codebooks/ is never created (Option B isolation)."""
        cfg = self._cfg_with(tmp_path, "cache/DPTO.csv", "cache/PROV.csv")

        results = generate_all(cfg, output_dir=tmp_path / "build")

        assert (tmp_path / "build" / "codebooks" / "DPTO.md").is_file()
        assert (tmp_path / "build" / "codebooks" / "PROV.md").is_file()
        root = tmp_path / "build" / "codebook.md"
        assert root.is_file()
        assert str(root) in results
        # Shared cache untouched by the Option B path.
        assert not (tmp_path / "cache" / "codebooks").exists()

    def test_output_dir_root_index_links_are_build_relative(self, tmp_path):
        """Root index links are relative to the output dir, not the cache."""
        cfg = self._cfg_with(tmp_path, "cache/DPTO.csv", "cache/Labels/etiquetas_a.csv")

        generate_all(cfg, output_dir=tmp_path / "build")

        content = (tmp_path / "build" / "codebook.md").read_text(encoding="utf-8")
        assert "[`codebooks/DPTO.md`](codebooks/DPTO.md)" in content
        assert "[`codebooks/Labels/etiquetas_a.md`](codebooks/Labels/etiquetas_a.md)" in content

    def test_default_mode_still_writes_cache(self, tmp_path):
        """Without output_dir, codebooks still go to cache/codebooks/ + root index."""
        cfg = self._cfg_with(tmp_path, "cache/DPTO.csv")

        results = generate_all(cfg)

        assert (tmp_path / "cache" / "codebooks" / "DPTO.md").is_file()
        assert (tmp_path / "cache" / "codebook.md").is_file()
        assert not (tmp_path / "codebook.md").exists()
        assert len(results) == 2  # 1 per-file + root index


# ══════════════════════════════════════════════════════════════════════════════
#  Phase 4.5 — Edge case tests
# ══════════════════════════════════════════════════════════════════════════════


class TestEdgeCases:
    def test_same_stem_collision_errors(self, tmp_path, capsys):
        """Two files with different extensions but same stem → ValueError, exit 1."""
        from sofer.model import DatasetConfig

        sub = tmp_path / "cache"
        sub.mkdir()
        (sub / "PROV.csv").write_text("a;b\n1;2\n", encoding="utf-8")
        (sub / "PROV.tsv").write_text("x\ty\n10\t20\n", encoding="utf-8")

        lines = [
            "[dataset]",
            'name = "test"',
            'repo_id = "u/test"',
            "",
            "[[file]]",
            'local = "cache/PROV.csv"',
            'remote = "PROV.csv"',
            "",
            "[[file]]",
            'local = "cache/PROV.tsv"',
            'remote = "PROV.tsv"',
            "",
        ]
        (tmp_path / "dataset.toml").write_text("\n".join(lines), encoding="utf-8")

        cfg = DatasetConfig.from_toml(tmp_path / "dataset.toml")
        with pytest.raises(ValueError, match="Collision"):
            generate_all(cfg)

        captured = capsys.readouterr()
        # Collision error names both sources on stderr
        assert "PROV.csv" in captured.err
        assert "PROV.tsv" in captured.err
        # No codebook written for colliding files
        assert not (tmp_path / "cache" / "codebooks" / "PROV.md").exists()

    def test_collision_partial_write_non_colliding(self, tmp_path, capsys):
        """Non-colliding codebooks are written; colliding ones are not; exit 1."""
        from sofer.model import DatasetConfig

        sub = tmp_path / "cache"
        sub.mkdir()
        (sub / "A.csv").write_text("x;y\n1;2\n", encoding="utf-8")
        (sub / "B.csv").write_text("p;q\n10;20\n", encoding="utf-8")
        (sub / "PROV.csv").write_text("a;b\n1;2\n", encoding="utf-8")
        (sub / "PROV.tsv").write_text("x\ty\n10\t20\n", encoding="utf-8")

        lines = [
            "[dataset]",
            'name = "test"',
            'repo_id = "u/test"',
            "",
            "[[file]]",
            'local = "cache/A.csv"',
            'remote = "A.csv"',
            "",
            "[[file]]",
            'local = "cache/B.csv"',
            'remote = "B.csv"',
            "",
            "[[file]]",
            'local = "cache/PROV.csv"',
            'remote = "PROV.csv"',
            "",
            "[[file]]",
            'local = "cache/PROV.tsv"',
            'remote = "PROV.tsv"',
            "",
        ]
        (tmp_path / "dataset.toml").write_text("\n".join(lines), encoding="utf-8")

        cfg = DatasetConfig.from_toml(tmp_path / "dataset.toml")
        codebooks_dir = tmp_path / "cache" / "codebooks"

        with pytest.raises(ValueError, match="Collision"):
            generate_all(cfg)

        # Non-colliding codebooks written
        assert (codebooks_dir / "A.md").exists()
        assert (codebooks_dir / "B.md").exists()
        # Colliding codebook NOT written
        assert not (codebooks_dir / "PROV.md").exists()
        # No root index on failure
        assert not (tmp_path / "cache" / "codebook.md").exists()
        assert not (tmp_path / "codebook.md").exists()
        captured = capsys.readouterr()
        assert "PROV.csv" in captured.err
        assert "PROV.tsv" in captured.err

    def test_no_index_on_failed_run(self, tmp_path, capsys):
        """Root codebook.md index is NOT generated when collision occurs."""
        from sofer.model import DatasetConfig

        sub = tmp_path / "cache"
        sub.mkdir()
        (sub / "DUP.csv").write_text("a;b\n1;2\n", encoding="utf-8")
        (sub / "DUP.tsv").write_text("x\ty\n10\t20\n", encoding="utf-8")

        lines = [
            "[dataset]",
            'name = "test"',
            'repo_id = "u/test"',
            "",
            "[[file]]",
            'local = "cache/DUP.csv"',
            'remote = "DUP.csv"',
            "",
            "[[file]]",
            'local = "cache/DUP.tsv"',
            'remote = "DUP.tsv"',
            "",
        ]
        (tmp_path / "dataset.toml").write_text("\n".join(lines), encoding="utf-8")

        cfg = DatasetConfig.from_toml(tmp_path / "dataset.toml")
        with pytest.raises(ValueError):
            generate_all(cfg)

        assert not (tmp_path / "cache" / "codebook.md").exists()
        assert not (tmp_path / "codebook.md").exists()

    def test_rel_stem_under_cache(self, tmp_path):
        """rel-stem preserves nested directory structure under cache/."""
        from sofer.model import DatasetConfig

        sub = tmp_path / "cache" / "Labels"
        sub.mkdir(parents=True)
        (sub / "etiquetas.csv").write_text("k;v\n1;2\n", encoding="utf-8")

        toml_path = _write_toml(tmp_path, ["cache/Labels/etiquetas.csv"])
        cfg = DatasetConfig.from_toml(toml_path)
        results = generate_all(cfg)

        codebook_path = tmp_path / "cache" / "codebooks" / "Labels" / "etiquetas.md"
        assert codebook_path.exists()
        assert str(codebook_path) in results

    def test_rel_stem_outside_cache(self, tmp_path):
        """Files outside cache/ fall back to relative_to(base_dir) for rel-stem."""
        from sofer.model import DatasetConfig

        # File at project root, not under cache/
        (tmp_path / "root_file.csv").write_text("x;y\n1;2\n", encoding="utf-8")

        toml_path = _write_toml(tmp_path, ["root_file.csv"])
        cfg = DatasetConfig.from_toml(toml_path)
        results = generate_all(cfg)

        # Falls back to rel to base_dir → codebooks placed under cache/codebooks/
        codebook_path = tmp_path / "cache" / "codebooks" / "root_file.md"
        assert codebook_path.exists()
        assert str(codebook_path) in results

    def test_empty_csv_minimal_codebook(self, tmp_path):
        csv_path = tmp_path / "header_only.csv"
        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            w = csv.writer(f, delimiter=";")
            w.writerow(["col_a", "col_b"])

        result = generate(str(csv_path), delimiter=_DEFAULT_DELIMITER, encoding=_DEFAULT_ENCODING)

        assert "# Codebook: header_only.csv" in result
        assert "**Rows:** 0" in result
        assert "**Columns:** 2" in result
        assert "| 1 | `col_a`" in result
        assert "| 2 | `col_b`" in result

    def test_parquet_with_bool_column(self, tmp_path):
        import pyarrow as pa
        import pyarrow.parquet as pq

        pq_path = tmp_path / "bools.parquet"
        table = pa.table({"flag": pa.array([True, False, True])})
        pq.write_table(table, pq_path)

        result = generate(str(pq_path), delimiter=_DEFAULT_DELIMITER, encoding=_DEFAULT_ENCODING)

        assert "Actual Type" in result
        assert "bool" in result

    def test_xlsx_single_file(self, tmp_path):
        import openpyxl

        xlsx_path = tmp_path / "sheet.xlsx"
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.append(["item", "price"])
        ws.append(["apple", 1.5])
        ws.append(["banana", 2.0])
        wb.save(xlsx_path)

        result = generate(str(xlsx_path), delimiter=_DEFAULT_DELIMITER, encoding=_DEFAULT_ENCODING)

        assert "# Codebook: sheet.xlsx" in result
        assert "Actual Type" in result
        assert "`item`" in result
        assert "`price`" in result

    def test_jsonl_single_file(self, tmp_path):
        jsonl_path = tmp_path / "data.jsonl"
        jsonl_path.write_text(
            '{"name": "Alice", "age": 30}\n{"name": "Bob", "age": 25}\n',
            encoding="utf-8",
        )

        result = generate(str(jsonl_path), delimiter=_DEFAULT_DELIMITER, encoding=_DEFAULT_ENCODING)

        assert "# Codebook: data.jsonl" in result
        assert "`name`" in result
        assert "`age`" in result


# ══════════════════════════════════════════════════════════════════════════════
#  Phase 4.6 — CLI tests
# ══════════════════════════════════════════════════════════════════════════════


class TestCodebookCLI:
    def _invoke(self, args, monkeypatch):
        import sofer.cli

        monkeypatch.setattr(sys, "argv", ["sofer", "codebook", *args])
        exc = None
        # noinspection PyBroadException
        try:
            sofer.cli.main()
        except SystemExit as e:
            exc = e
        return exc

    def test_csv_optional_allows_all_files(self, tmp_path, monkeypatch):
        csv_path = tmp_path / "t.csv"
        csv_path.write_text("x;y\n1;2\n", encoding="utf-8")

        exc = self._invoke([str(csv_path)], monkeypatch)
        assert exc is not None
        assert exc.code == 0

    def test_all_files_without_csv_succeeds(self, tmp_path, monkeypatch):
        csv_path = tmp_path / "d.csv"
        csv_path.write_text("k\n1\n", encoding="utf-8")

        lines = [
            "[dataset]",
            'name = "test"',
            'repo_id = "u/test"',
            "",
            "[[file]]",
            'local = "d.csv"',
            'remote = "d.csv"',
            "",
        ]
        (tmp_path / "dataset.toml").write_text("\n".join(lines), encoding="utf-8")

        monkeypatch.chdir(tmp_path)
        exc = self._invoke(["--all-files"], monkeypatch)
        assert exc is not None
        assert exc.code == 0

    def test_both_args_error(self, tmp_path, monkeypatch, capsys):
        csv_path = tmp_path / "t.csv"
        csv_path.write_text("x\n1\n", encoding="utf-8")
        (tmp_path / "dataset.toml").write_text(
            '[dataset]\nname="t"\nrepo_id="u/t"\n[[file]]\nlocal="t.csv"\nremote="t.csv"\n',
            encoding="utf-8",
        )

        monkeypatch.chdir(tmp_path)
        exc = self._invoke([str(csv_path), "--all-files"], monkeypatch)
        assert exc is not None
        assert exc.code == 1
        captured = capsys.readouterr()
        assert "cannot be used" in captured.err

    def test_no_args_error(self, tmp_path, monkeypatch, capsys):
        monkeypatch.chdir(tmp_path)
        exc = self._invoke([], monkeypatch)
        assert exc is not None
        assert exc.code == 1
        captured = capsys.readouterr()
        assert "Must specify a FILE" in captured.err

    def test_positional_with_output(self, tmp_path, monkeypatch):
        csv_path = tmp_path / "t.csv"
        csv_path.write_text("a\n1\n", encoding="utf-8")
        out = tmp_path / "out.md"

        exc = self._invoke([str(csv_path), "-o", str(out)], monkeypatch)
        assert exc is not None
        assert exc.code == 0
        assert out.exists()

    def test_malformed_toml_exits_1(self, tmp_path, monkeypatch, capsys):
        (tmp_path / "dataset.toml").write_text("bad = [[[[\n", encoding="utf-8")

        monkeypatch.chdir(tmp_path)
        exc = self._invoke(["--all-files"], monkeypatch)
        assert exc is not None
        assert exc.code == 1
        captured = capsys.readouterr()
        assert "TOML" in captured.err

    def test_codebook_cli_collision_exits_1(self, tmp_path, monkeypatch, capsys):
        """CLI catches ValueError from generate_all and exits 1 on collision."""
        sub = tmp_path / "cache"
        sub.mkdir()
        (sub / "DUP.csv").write_text("a;b\n1;2\n", encoding="utf-8")
        (sub / "DUP.tsv").write_text("x\ty\n10\t20\n", encoding="utf-8")

        lines = [
            "[dataset]",
            'name = "test"',
            'repo_id = "u/test"',
            "",
            "[[file]]",
            'local = "cache/DUP.csv"',
            'remote = "DUP.csv"',
            "",
            "[[file]]",
            'local = "cache/DUP.tsv"',
            'remote = "DUP.tsv"',
            "",
        ]
        (tmp_path / "dataset.toml").write_text("\n".join(lines), encoding="utf-8")

        monkeypatch.chdir(tmp_path)
        exc = self._invoke(["--all-files"], monkeypatch)
        assert exc is not None
        assert exc.code == 1
        captured = capsys.readouterr()
        assert "Collision" in captured.err or "collision" in captured.err.lower()


# ══════════════════════════════════════════════════════════════════════════════
#  Phase 1 (sofer-mcp-server) — empty-input placeholder + dataset-driven
#  delimiter/encoding seam in generate_all (adv5, D2/MSP-R10)
# ══════════════════════════════════════════════════════════════════════════════


class TestEmptyInputPlaceholder:
    """Empty/headerless inputs render a marker codebook instead of crashing."""

    def test_build_markdown_empty_headers_placeholder(self):
        result = _build_markdown([], [], None, "empty.csv")
        assert "**No data rows found** — the file is empty or headerless." in result
        assert "# Codebook: empty.csv" in result

    def test_generate_empty_csv_returns_placeholder(self, tmp_path):
        csv_path = tmp_path / "empty.csv"
        csv_path.write_text("", encoding="utf-8")

        result = generate(str(csv_path), delimiter=_DEFAULT_DELIMITER, encoding=_DEFAULT_ENCODING)

        assert "**No data rows found** — the file is empty or headerless." in result

    def test_generate_empty_jsonl_returns_placeholder(self, tmp_path):
        jsonl_path = tmp_path / "empty.jsonl"
        jsonl_path.write_text("", encoding="utf-8")

        result = generate(str(jsonl_path), delimiter=_DEFAULT_DELIMITER, encoding=_DEFAULT_ENCODING)

        assert "**No data rows found** — the file is empty or headerless." in result

    def test_generate_header_only_csv_still_renders_columns(self, tmp_path):
        """A header-only file is NOT 'headerless' — columns keep rendering."""
        csv_path = tmp_path / "header_only.csv"
        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            w = csv.writer(f, delimiter=";")
            w.writerow(["col_a", "col_b"])

        result = generate(str(csv_path), delimiter=_DEFAULT_DELIMITER, encoding=_DEFAULT_ENCODING)

        assert "**No data rows found**" not in result
        assert "| 1 | `col_a`" in result


class TestGenerateAllDelimiterSeam:
    """generate_all resolves None → cfg.csv_delimiter/csv_encoding ([meta])."""

    def _toml(self, tmp_path, delimiter: str) -> Path:
        lines = [
            "[dataset]",
            'name = "delim-ds"',
            'repo_id = "user/delim-ds"',
            "",
            "[meta]",
            f'csv_delimiter = "{delimiter}"',
            "",
            "[[file]]",
            'local = "data.csv"',
            'remote = "data.csv"',
            "",
        ]
        toml_path = tmp_path / "dataset.toml"
        toml_path.write_text("\n".join(lines), encoding="utf-8")
        return toml_path

    def test_uses_cfg_meta_delimiter_when_none(self, tmp_path):
        """Rule-3 fix: [meta] csv_delimiter=\",\" is honored, not the hardcoded ';'."""
        from sofer.model import DatasetConfig

        (tmp_path / "data.csv").write_text("a,b\n1,2\n3,4\n", encoding="utf-8-sig")
        cfg = DatasetConfig.from_toml(self._toml(tmp_path, ","))

        results = generate_all(cfg)

        codebook_path = tmp_path / "cache" / "codebooks" / "data.md"
        assert str(codebook_path) in results
        content = codebook_path.read_text(encoding="utf-8")
        # Two comma-separated columns, not one 'a,b' column.
        assert "| 1 | `a`" in content
        assert "| 2 | `b`" in content
        assert "`a,b`" not in content

    def test_explicit_delimiter_overrides_cfg(self, tmp_path):
        """An explicit delimiter argument beats the [meta] value."""
        from sofer.model import DatasetConfig

        (tmp_path / "data.csv").write_text("a;b\n1;2\n", encoding="utf-8-sig")
        cfg = DatasetConfig.from_toml(self._toml(tmp_path, ","))

        results = generate_all(cfg, delimiter=";")

        codebook_path = tmp_path / "cache" / "codebooks" / "data.md"
        assert str(codebook_path) in results
        content = codebook_path.read_text(encoding="utf-8")
        assert "| 1 | `a`" in content
        assert "| 2 | `b`" in content


# ── Multisheet XLSX (CB-R09) ──────────────────────────────────────


def _make_xlsx(path: Path, sheets: dict[str, list[list[object]]]) -> None:
    """Helper: create an xlsx with given sheets mapping name -> rows (header first)."""
    import openpyxl

    wb = openpyxl.Workbook()
    first = True
    for name, rows in sheets.items():
        if first:
            ws = wb.active
            ws.title = name
            first = False
        else:
            ws = wb.create_sheet(title=name)
        for row in rows:
            ws.append(row)
    wb.save(path)


class TestCodebookMultisheet:
    def test_read_xlsx_sheets_single(self, tmp_path):
        p = tmp_path / "a.xlsx"
        _make_xlsx(p, {"Ventas": [["h1", "h2"], ["a", "b"]]})
        from sofer.codebook import _read_xlsx_sheets

        sheets = _read_xlsx_sheets(str(p))
        assert len(sheets) == 1
        assert "ventas" in sheets
        headers, _cols, _dtypes = sheets["ventas"]
        assert headers == ["h1", "h2"]

    def test_read_xlsx_sheets_two(self, tmp_path):
        p = tmp_path / "rep.xlsx"
        _make_xlsx(p, {"Ventas": [["a", "b"], ["1", "2"]], "Costos": [["c"], ["3"]]})
        from sofer.codebook import _read_xlsx_sheets

        sheets = _read_xlsx_sheets(str(p))
        assert len(sheets) == 2
        assert "ventas" in sheets
        assert "costos" in sheets

    def test_dedup_ventas(self, tmp_path):
        # Use names that sanitize identically but are distinct for openpyxl
        # (openpyxl auto-renames "Ventas"/"VENTAS" to "Ventas"/"VENTAS1")
        p = tmp_path / "d.xlsx"
        _make_xlsx(p, {"Ventas": [["h"], ["x"]], "Ventas!": [["h"], ["y"]]})
        from sofer.codebook import _read_xlsx_sheets

        sheets = _read_xlsx_sheets(str(p))
        assert "ventas" in sheets
        assert "ventas_2" in sheets

    def test_empty_sheet_placeholder(self, tmp_path):
        p = tmp_path / "e.xlsx"
        _make_xlsx(p, {"Ventas": [["h"], ["x"]], "Empty": []})
        from sofer.codebook import _build_markdown, _read_xlsx_sheets

        sheets = _read_xlsx_sheets(str(p))
        # Empty sheet yields placeholder
        headers, cols, dtypes = sheets["empty"]
        assert headers == []
        # building markdown gives placeholder
        md = _build_markdown(headers, cols, dtypes, str(p))
        assert "**No data rows found**" in md

    def test_generate_single_stays_stem(self, tmp_path):
        from sofer.model import DatasetConfig

        xlsx = tmp_path / "report.xlsx"
        _make_xlsx(xlsx, {"Ventas": [["a"], ["1"]]})
        cfg = DatasetConfig(name="ds", repo_id="u/ds", files=[], _base_dir=tmp_path)
        cfg.files.append(
            __import__("sofer.model", fromlist=["FileEntry"]).FileEntry(
                local=xlsx, remote="report.xlsx"
            )
        )
        # Use manual cfg with files - bypass from_toml
        from sofer.codebook import generate_all

        res = generate_all(cfg)
        # should be stem.md not __ventas
        assert any("report.md" in r for r in res)
        assert not any("__ventas" in r for r in res)

    def test_generate_two_files(self, tmp_path):
        from sofer.model import DatasetConfig, FileEntry

        xlsx = tmp_path / "report.xlsx"
        _make_xlsx(xlsx, {"Ventas": [["a"], ["1"]], "Costos": [["b"], ["2"]]})
        cfg = DatasetConfig(
            name="ds",
            repo_id="u/ds",
            files=[FileEntry(local=xlsx, remote="report.xlsx")],
            _base_dir=tmp_path,
        )
        from sofer.codebook import generate_all

        res = generate_all(cfg)
        assert any("report__ventas.md" in r for r in res)
        assert any("report__costos.md" in r for r in res)
        # index counts sheets
        idx = (tmp_path / "cache" / "codebook.md").read_text(encoding="utf-8")
        assert "**Tables:** 2" in idx

    def test_batch_n_plus_index(self, tmp_path):
        from sofer.model import DatasetConfig, FileEntry

        (tmp_path / "a.csv").write_text("x;y\n1;2\n", encoding="utf-8-sig")
        xlsx = tmp_path / "report.xlsx"
        _make_xlsx(xlsx, {"Ventas": [["a"], ["1"]], "Costos": [["b"], ["2"]]})
        cfg = DatasetConfig(
            name="ds",
            repo_id="u/ds",
            files=[
                FileEntry(local=tmp_path / "a.csv", remote="a.csv"),
                FileEntry(local=xlsx, remote="report.xlsx"),
            ],
            _base_dir=tmp_path,
        )
        from sofer.codebook import generate_all

        res = generate_all(cfg)
        # 1 csv + 2 sheets = 3 + index = 4
        assert len([r for r in res if r.endswith(".md") and "codebook.md" not in r]) == 3
        idx = (tmp_path / "cache" / "codebook.md").read_text(encoding="utf-8")
        assert "**Tables:** 3" in idx

    def test_collision_dual_guard(self, tmp_path):
        import pytest

        from sofer.model import DatasetConfig, FileEntry

        # a_ventas.csv -> a_ventas.md ; a__ventas.xlsx -> a__ventas.md (normalized to a_ventas.md)  # noqa: E501
        csv_path = tmp_path / "a_ventas.csv"
        csv_path.write_text("x\n1\n", encoding="utf-8-sig")
        xlsx = tmp_path / "a.xlsx"
        _make_xlsx(
            xlsx, {"Ventas": [["h"], ["x"]], "Costos": [["h2"], ["y"]]}
        )  # will produce a__ventas and a__costos
        # Collision: a.xlsx sheet ventas -> a__ventas vs a_ventas.csv -> same normalized  # noqa: E501
        # rel_stem "a" + "__ventas" vs "a_ventas" -> both normalized to "a_ventas"
        # So create a.xlsx and a_ventas.csv
        cfg = DatasetConfig(
            name="ds",
            repo_id="u/ds",
            files=[
                FileEntry(local=csv_path, remote="a_ventas.csv"),
                FileEntry(local=xlsx, remote="a.xlsx"),
            ],
            _base_dir=tmp_path,
        )
        from sofer.codebook import generate_all

        with pytest.raises(ValueError, match="Collision"):
            generate_all(cfg)


def test_generate_all_max_sample_override(tmp_path):
    """#155: generate_all threads max_sample into per-file codebooks."""
    from sofer.model import DatasetConfig, FileEntry

    (tmp_path / "data.csv").write_text("col_a;col_b\n1;x\n2;y\n3;z\n", encoding="utf-8-sig")
    cfg = DatasetConfig(
        name="ds",
        repo_id="u/ds",
        files=[FileEntry(local=tmp_path / "data.csv", remote="data.csv")],
        _base_dir=tmp_path,
    )
    out = tmp_path / "build"
    generate_all(cfg, output_dir=out, max_sample=1)
    cb = out / "codebooks" / "data.md"
    assert "Analysed rows:** 1 (sample)" in cb.read_text(encoding="utf-8")
