"""Tests for data_uploader.codebook — CSV analysis and markdown generation."""

import csv

from data_uploader.codebook import _infer_type, generate, infer_column_type

# ── _infer_type ───────────────────────────────────────────────────────────────


class TestInferType:
    def test_numeric(self):
        assert _infer_type(["1", "2", "3", "4"]) == "numeric"

    def test_numeric_with_decimals(self):
        assert _infer_type(["1,5", "2,0", "3,7"]) == "numeric"

    def test_categorical(self):
        assert _infer_type(["red", "blue", "green", "red"]) == "categorical/text"

    def test_mixed_mostly_numeric(self):
        vals = ["1", "2", "three", "4"]
        assert "mixed" in _infer_type(vals)

    def test_empty_values(self):
        assert _infer_type(["", "NA", "MISSING"]) == "categorical/text"

    def test_mixed_with_missing(self):
        vals = ["10", "", "20", "NA", "30"]
        # 3 numeric out of 5 → 0.6 → "mixed (mostly numeric)"
        assert "mixed" in _infer_type(vals)

    def test_all_missing(self):
        assert _infer_type(["NA", "NA", ""]) == "categorical/text"

    def test_single_value(self):
        assert _infer_type(["42"]) == "numeric"
        assert _infer_type(["hello"]) == "categorical/text"


class TestInferColumnType:
    """Public ``infer_column_type`` — same logic as private ``_infer_type``."""

    def test_public_api_exists(self):
        """infer_column_type should be importable and callable."""
        assert callable(infer_column_type)

    def test_returns_same_as_private(self):
        """infer_column_type should produce identical results to _infer_type."""
        cases = [
            (["1", "2", "3"], "numeric"),
            (["red", "blue"], "categorical/text"),
            (["1", "two", "3"], "mixed (mostly numeric)"),
            (["NA", "", "MISSING"], "categorical/text"),
        ]
        for values, expected in cases:
            assert infer_column_type(values) == expected
            assert infer_column_type(values) == _infer_type(values)


# ── generate ──────────────────────────────────────────────────────────────────


class TestGenerate:
    def test_basic_codebook_structure(self, tmp_path):
        """Generated codebook should contain expected markdown sections."""
        csv_path = tmp_path / "test.csv"
        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            w = csv.writer(f, delimiter=";")
            w.writerow(["id", "name", "age"])
            w.writerow(["1", "Alice", "30"])
            w.writerow(["2", "Bob", "25"])

        result = generate(str(csv_path))

        assert "# Codebook: test.csv" in result
        assert "| # | Column" in result
        assert "`id`" in result
        assert "`name`" in result
        assert "`age`" in result
        assert "Generated by data-uploader" in result

    def test_codebook_with_missing_values(self, tmp_path):
        """Missing values should be reflected in the missing % column."""
        csv_path = tmp_path / "missing.csv"
        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            w = csv.writer(f, delimiter=";")
            w.writerow(["val"])
            w.writerow(["10"])
            w.writerow(["NA"])
            w.writerow([""])
            w.writerow(["30"])

        result = generate(str(csv_path), max_sample=10)
        # 2 out of 4 data rows are missing → 50%
        assert "50.0%" in result or "50%" in result

    def test_codebook_writes_to_file(self, tmp_path):
        """When output_path is given, the codebook should be written to disk."""
        csv_path = tmp_path / "data.csv"
        csv_path.write_text("x;y\n1;2\n", encoding="utf-8")
        out_path = tmp_path / "codebook.md"

        result = generate(str(csv_path), output_path=str(out_path))
        assert out_path.exists()
        content = out_path.read_text(encoding="utf-8")
        assert "Codebook: data.csv" in content
        # Also returned as string
        assert result == content

    def test_codebook_row_count(self, tmp_path):
        """Row count should be accurate."""
        csv_path = tmp_path / "rows.csv"
        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            w = csv.writer(f, delimiter=";")
            w.writerow(["col"])
            for i in range(100):
                w.writerow([i])
        result = generate(str(csv_path), max_sample=1000)
        assert "**Rows:** 100" in result

    def test_large_file_samples(self, tmp_path):
        """Files larger than max_sample should note they're sampled."""
        csv_path = tmp_path / "large.csv"
        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            w = csv.writer(f, delimiter=";")
            w.writerow(["x"])
            for i in range(5000):
                w.writerow([i])

        result = generate(str(csv_path), max_sample=100)
        assert "sample" in result.lower()

    def test_small_file_is_full_scan(self, tmp_path):
        """Files smaller than max_sample should say 'full scan'."""
        csv_path = tmp_path / "small.csv"
        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            w = csv.writer(f, delimiter=";")
            w.writerow(["x"])
            for i in range(10):
                w.writerow([i])

        result = generate(str(csv_path), max_sample=100)
        assert "full scan" in result.lower()

    def test_numeric_column_type_in_codebook(self, tmp_path):
        """A numeric column should be labelled 'numeric'."""
        csv_path = tmp_path / "nums.csv"
        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            w = csv.writer(f, delimiter=";")
            w.writerow(["value"])
            for i in range(20):
                w.writerow([i])

        result = generate(str(csv_path))
        assert "numeric" in result

    def test_categorical_column_type_in_codebook(self, tmp_path):
        """A text column should be labelled 'categorical/text'."""
        csv_path = tmp_path / "cats.csv"
        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            w = csv.writer(f, delimiter=";")
            w.writerow(["color"])
            for v in ["red", "blue", "green"] * 10:
                w.writerow([v])

        result = generate(str(csv_path))
        assert "categorical/text" in result
