"""
Delivery pipeline for a prepared dataset package (network + local).

``publish`` takes the mirror-layout package produced by
:func:`sofer.prepare.prepare` (the dataset's build directory) and delivers
it to a target:

- ``target="hf"`` (default): gates on the CLI-computed quality report
  (failures block delivery before any network call), ensures the HF
  repository exists, inspects it, prints a diff summary, applies overwrite
  protection, stages the *planned artifacts only* from the output directory,
  and pushes the whole tree with a single ``HfApi.upload_folder`` call
  (PUB-01).  Remote inspection is fail-closed (PUB-05): a repository that
  does not exist reads as empty, but any OTHER inspection or ``create_repo``
  failure aborts the publish with rc 1 before upload — inspection failure is
  never treated as an empty repo, so overwrite protection always sees the
  true remote state.  A post-upload split report is printed.
- ``target="local"``: copies the package to ``--output`` with zero network
  access; without ``--output``, prints an in-place package summary without
  mutating anything (PUB-02).

When the output directory has no Parquet files, or the TOML / any declared
source file is newer than the newest Parquet, ``publish`` runs
:func:`sofer.prepare.prepare` automatically first (PUB-03) — always with
``force=True``, since regenerating into the same directory is expected.
``--dry-run`` prints the diff and split report from the planned remotes and
never prepares, copies, or touches the network (PUB-04).

Orchestration flow (delivery half of the legacy ``uploader.upload``):

    1. Resolve the source package directory (``prepare.resolve_output_dir``).
    2. Auto-prepare when artifacts are stale or missing (PUB-03) — skipped
       under ``--dry-run`` (PUB-04).
    3. ``--dry-run``: diff summary + split-mapping validation + split report
       from the expanded planned remotes, then stop.
    4. ``target="local"``: copy planned artifacts + compliance + codebooks
       from the build directory to ``--output`` (or print the in-place
       summary when ``--output`` is omitted).
    5. ``target="hf"``: quality gate -> ``_ensure_repo`` -> ``_inspect_repo``
       -> diff summary (expanded, PUB-10) -> overwrite protection (per-sheet)
       -> split-mapping validation (count N) -> stage expanded artifacts
       from the output directory -> single ``_hf_upload_folder`` call
       -> post-upload split report.

The planned set is derived via :func:`sofer._mirror.expanded_planned_remotes`
when the mirror exists (ground truth for multi-sheet XLSX, PUB-10), else via
:func:`planned_remotes` logical placeholder (dry-run before prepare).

Delivery helpers (``_ensure_repo``, ``_inspect_repo``, ``_repo_diff_summary``,
``_check_overwrite_protection``, ``_hf_upload``, ``_hf_upload_folder``,
``_print_split_report``, ``_print_split_mapping_validation``) now live in this
module (moved from ``uploader.py`` in PR 4).  The shared ``HfApi`` instance
``_api`` lives here too — the only place the Hub is contacted.
"""

from __future__ import annotations

import shutil
import sys
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .checks import ValidationReport
    from .model import DatasetConfig

from huggingface_hub import HfApi
from huggingface_hub.utils import RepositoryNotFoundError

from . import config
from ._mirror import copy_to_mirror, expanded_planned_remotes, planned_remotes
from .prepare import prepare, resolve_output_dir
from .splits import detect_splits, validate_layout, validate_split_mapping

_api = HfApi()

# Auto-generated compliance files that always overwrite silently (PUB-05).
# These are NOT protected by _check_overwrite_protection: README.md, LICENSE,
# codebook.md, and every codebooks/**/*.md path.
_AUTO_GENERATED: frozenset[str] = frozenset({"readme.md", "license", "codebook.md"})
_AUTO_GENERATED_PREFIXES: tuple[str, ...] = ("codebooks/",)


def _is_auto_generated(remote: str) -> bool:
    """Return ``True`` when *remote* is an auto-generated compliance file.

    Auto-generated files — ``README.md``, ``LICENSE``, ``codebook.md`` and
    ``codebooks/**/*.md`` — always overwrite the remote without prompting
    (PUB-05).  Matching is case-insensitive, and ``codebooks/`` is a prefix
    match so every per-file codebook page is covered.

    Args:
        remote: Remote path in the repository (POSIX separators).

    Returns:
        ``True`` when the file is regenerated by ``prepare`` and should
        never be protected by overwrite protection.
    """
    lower = remote.lower()
    return lower in _AUTO_GENERATED or lower.startswith(_AUTO_GENERATED_PREFIXES)


# ── Delivery helpers (moved from uploader.py, PR 4) ────────────────────────────


def _ensure_repo(cfg: DatasetConfig, api: HfApi | None = None) -> None:
    """Create the HF repository if it doesn't exist (idempotent, fail-closed).

    A ``create_repo`` failure for a reason other than "already exists" (e.g.
    an authentication error, a quota violation, or a network failure) RAISES
    instead of printing and continuing — proceeding after a failed
    ``create_repo`` could upload into a repo the caller cannot even manage.

    Args:
        cfg: Dataset configuration (``repo_id``, ``repo_type``, ``private``).
        api: Optional :class:`HfApi` instance (with token); defaults to module ``_api``.

    Raises:
        Exception: Any ``create_repo`` failure that is not an already-exists
            response (the already-exists case prints and returns).
    """
    target_api = api if api is not None else _api
    try:
        target_api.create_repo(
            repo_id=cfg.repo_id,
            repo_type=cfg.repo_type,
            private=cfg.private,
            exist_ok=True,
        )
    except Exception as exc:
        msg = str(exc).lower()
        if "already exists" in msg:
            print(f"  i  Repository already exists: {cfg.repo_id}")
        else:
            raise


def _hf_upload(
    repo_id: str,
    local_path: str | Path,
    remote_path: str,
    repo_type: str,
    api: HfApi | None = None,
) -> bool:
    """Upload a single file to Hugging Face Hub via ``HfApi.upload_file()``.

    Args:
        repo_id:    Target repository (``user/repo``).
        local_path: Local file to upload.
        remote_path: Path of the file inside the repository.
        repo_type:  Repository type (``"dataset"``, ``"model"``, ...).
        api: Optional :class:`HfApi` instance (with token); defaults to module ``_api``.

    Returns:
        ``True`` on success, ``False`` on failure (error already printed).
    """
    target_api = api if api is not None else _api
    label = Path(local_path).name
    print(f"  \u2191  {label}  \u2192  {remote_path}")
    try:
        target_api.upload_file(
            path_or_fileobj=str(local_path),
            path_in_repo=remote_path,
            repo_id=repo_id,
            repo_type=repo_type,
        )
        print(f"  \u2713  {label}")
        return True
    except Exception as exc:
        print(f"  \u2717  {exc}")
        return False


def _hf_upload_folder(
    repo_id: str,
    local_path: str | Path,
    remote_path: str,
    repo_type: str,
    api: HfApi | None = None,
) -> bool:
    """Upload a directory recursively via ``HfApi.upload_folder()``.

    Args:
        repo_id:     Target repository (``user/repo``).
        local_path:  Local directory whose contents are uploaded.
        remote_path: Prefix path inside the repository.
        repo_type:   Repository type (``"dataset"``, ``"model"``, ...).
        api: Optional :class:`HfApi` instance (with token); defaults to module ``_api``.

    Returns:
        ``True`` on success, ``False`` on failure (error already printed).
    """
    target_api = api if api is not None else _api
    label = Path(local_path).name
    print(f"  \u2191  {label}/  \u2192  {remote_path}")
    try:
        target_api.upload_folder(
            folder_path=str(local_path),
            path_in_repo=remote_path,
            repo_id=repo_id,
            repo_type=repo_type,
        )
        print(f"  \u2713  {label}/")
        return True
    except Exception as exc:
        print(f"  \u2717  {exc}")
        return False


def _inspect_repo(cfg: DatasetConfig, api: HfApi | None = None) -> list[str]:
    """Query the HF repo and return a list of existing remote file paths.

    Fail-closed (PUB-05): a :class:`RepositoryNotFoundError` — the repo does
    not exist yet, or is empty — returns an empty list; ANY other failure
    (network, authentication, rate limit) RAISES. Swallowing those into
    ``[]`` would make the repo look empty, so overwrite protection would
    find nothing to protect and the upload could overwrite protected
    remotes — inspection failure is NEVER treated as an empty repo.

    Args:
        cfg: Dataset configuration (``repo_id``, ``repo_type``).
        api: Optional :class:`HfApi` instance (with token); defaults to module ``_api``.

    Returns:
        The list of existing remote paths; empty only when the repo does
        not exist (or has no files).

    Raises:
        Exception: Any inspection failure other than
            :class:`RepositoryNotFoundError`.
    """
    target_api = api if api is not None else _api
    try:
        existing = target_api.list_repo_files(repo_id=cfg.repo_id, repo_type=cfg.repo_type)
        return list(existing)
    except RepositoryNotFoundError:
        return []


def _repo_diff_summary(
    cfg: DatasetConfig,
    existing_files: list[str],
    keep_csv: bool,
    codebook_remotes: list[str] | None = None,
    staging_dir: Path | None = None,
) -> str:
    """Build a human-readable diff of what will be added vs modified.

    Derives the planned set via :func:`sofer._mirror.expanded_planned_remotes`
    when *staging_dir* exists (ground truth, PUB-10), otherwise via the
    logical :func:`planned_remotes` placeholder.  Recursive entries are
    rendered with a trailing ``*`` marker.

    Args:
        cfg:            Dataset configuration.
        existing_files: Files already in the repo (from :func:`_inspect_repo`).
        keep_csv:       Whether original CSVs will be uploaded alongside Parquet.
        codebook_remotes: Optional planned codebook remote paths (RC-C01).
        staging_dir:    Mirror layout root for XLSX expansion.  ``None`` or
            not a directory falls back to the logical placeholder.

    Returns:
        A multiline string suitable for printing.
    """
    existing_set = {f.lower() for f in existing_files}

    if staging_dir is not None and staging_dir.is_dir():
        raw_planned = expanded_planned_remotes(cfg, keep_csv, staging_dir)
    else:
        raw_planned = planned_remotes(cfg, keep_csv)

    # Build display list: README/LICENSE plus expanded remotes with * for recursive
    recursive_set = {e.remote.rstrip("/\\").lower() for e in cfg.files if e.recursive}
    planned: list[str] = ["README.md", "LICENSE"]
    for remote in raw_planned:
        if remote.lower() in recursive_set:
            planned.append(f"{remote}*")
        else:
            planned.append(remote)

    # ── Codebook remotes (RC-C01) ──
    if codebook_remotes:
        planned.extend(codebook_remotes)

    new = [p for p in planned if p.lower() not in existing_set]
    modified = [p for p in planned if p.lower() in existing_set]

    lines: list[str] = []
    lines.append("  Repo inspection:")
    if not existing_files:
        lines.append("    (repo is empty or does not exist yet)")
    else:
        lines.append(f"    {len(existing_files)} file(s) already in repo")

    if new:
        lines.append(f"    + {len(new)} file(s) will be ADDED:")
        for f in new[: config.REPORT_MAX_ITEMS]:
            lines.append(f"      + {f}")
        if len(new) > config.REPORT_MAX_ITEMS:
            lines.append(f"      … and {len(new) - config.REPORT_MAX_ITEMS} more")

    if modified:
        lines.append(f"    ~ {len(modified)} file(s) will be OVERWRITTEN:")
        for f in modified[: config.REPORT_MAX_MODIFIED]:
            lines.append(f"      ~ {f}")
        if len(modified) > config.REPORT_MAX_MODIFIED:
            lines.append(f"      … and {len(modified) - config.REPORT_MAX_MODIFIED} more")

    return "\n".join(lines)


def _check_overwrite_protection(
    existing_files: list[str],
    force: bool,
    planned_files: list[str] | None = None,
) -> set[str]:
    """Check whether planned files already exist and gate overwrites.

    Auto-generated files (:data:`_AUTO_GENERATED`, matched by
    :func:`_is_auto_generated`) always pass through unprotected — they are
    regenerated on every run (PUB-05).

    When *planned_files* is provided, only those files are candidates for
    protection (the data files ``publish`` is about to deliver); without it,
    the legacy README/LICENSE pair is checked for backward compatibility.

    When *force* is ``True``, skip the check entirely.

    In interactive mode: warn and ask for confirmation per file.
    In non-interactive mode: warn and skip the protected files.

    Args:
        existing_files: Remote paths already present in the repository.
        force:          When ``True``, skip the check entirely.
        planned_files:  Remote paths that would be delivered; a file in this
                        list that already exists and is not auto-generated is
                        protected.  ``None`` keeps the legacy
                        README/LICENSE-only behavior.

    Returns:
        Set of filenames that SHOULD be skipped (protected).
    """
    if force:
        return set()

    protected: set[str] = set()
    existing_set = {f.lower() for f in existing_files}
    interactive = sys.stdin.isatty()

    candidates = planned_files if planned_files is not None else ("README.md", "LICENSE")

    for filename in candidates:
        if _is_auto_generated(filename):
            continue
        if filename.lower() in existing_set:
            if interactive:
                try:
                    answer = input(
                        f"  [!] {filename} already exists in the repo. Overwrite? [y/N]: "
                    )
                    if answer.strip().lower() not in ("y", "yes"):
                        print(f"  i  {filename}: skipped (protected by user)")
                        protected.add(filename.lower())
                except (EOFError, KeyboardInterrupt):
                    print(f"\n  i  {filename}: skipped (non-interactive input)")
                    protected.add(filename.lower())
            else:
                print(
                    f"  [!] {filename} already exists in the repo. "
                    f"Skipping overwrite (non-interactive mode — use --force to override)."
                )
                protected.add(filename.lower())

    return protected


def _print_split_report(report: object) -> None:
    """Print a human-readable split detection summary.

    Args:
        report: A :class:`sofer.splits.SplitReport` (ignored when ``None``
                or a different type).
    """
    from .splits import SplitReport

    if not isinstance(report, SplitReport):
        return

    if not report.splits:
        return

    print("\n  Split detection:")
    for s in report.splits:
        print(f"    [{s.name}] {len(s.files)} file(s)")
        for f in s.files[: config.REPORT_MAX_MODIFIED]:
            print(f"      - {f}")
        if len(s.files) > config.REPORT_MAX_MODIFIED:
            print(f"      … and {len(s.files) - config.REPORT_MAX_MODIFIED} more")

    if report.unclassified:
        print(f"    [?] {len(report.unclassified)} file(s) unclassified")

    for w in report.warnings:
        print(f"    [!] {w}")

    # Layout validation
    layout_warnings = validate_layout(
        [f for s in report.splits for f in s.files] + report.unclassified
    )
    for w in layout_warnings:
        print(f"    [!] {w}")


def _print_split_mapping_validation(remotes: list[str]) -> None:
    """Print split mapping compatibility warnings for the planned upload.

    Args:
        remotes: Planned remote paths being delivered.
    """
    mapping_warnings = validate_split_mapping(remotes)
    if mapping_warnings:
        print("\n  Split mapping validation:")
        for w in mapping_warnings:
            print(f"    [!] {w}")


def _needs_prepare(cfg: DatasetConfig, output_dir: Path) -> bool:
    """Return ``True`` when the package in *output_dir* is stale or missing.

    The signal keys on *inputs*, never on hand-edited artifacts (PUB-03):
    the package needs regenerating when

    - the output directory has no ``.parquet`` files (existence fallback), or
    - ``dataset.toml`` was modified after the newest Parquet, or
    - any declared source file (all supported formats: CSV, TSV, Parquet,
      Excel, JSONL) was modified after the newest Parquet.

    Args:
        cfg:        Dataset configuration.
        output_dir: Prepared package directory being checked.

    Returns:
        ``True`` when ``prepare`` should regenerate the package.
    """
    parquets = sorted(output_dir.rglob("*.parquet"))
    if not parquets:
        return True
    newest = max(p.stat().st_mtime for p in parquets)

    base = cfg._base_dir if cfg._base_dir else Path.cwd()
    toml_path = base / config.DEFAULT_CONFIG_NAME
    if toml_path.is_file() and toml_path.stat().st_mtime > newest:
        return True

    sources = [e.resolve(base) for e in cfg.files if e.resolve(base).exists()]
    if sources and max(s.stat().st_mtime for s in sources) > newest:
        return True

    return False


def _collect_codebook_remotes(output_dir: Path) -> list[str]:
    """Return the codebook remote paths present in *output_dir*.

    Codebooks follow the mirror layout: per-file pages under
    ``codebooks/**/*.md`` plus the root ``codebook.md`` index (RC-C01).
    Used for the hf diff summary and the staged package.

    Args:
        output_dir: Prepared package directory (mirror layout root).

    Returns:
        Codebook remote paths, sorted.
    """
    remotes: list[str] = []
    codebooks_dir = output_dir / config.CODEBOOKS_DIR
    if codebooks_dir.is_dir():
        for cb in sorted(codebooks_dir.rglob("*.md")):
            remotes.append(cb.relative_to(output_dir).as_posix())
    if (output_dir / "codebook.md").is_file():
        remotes.append("codebook.md")
    return remotes


def _copy_package(
    cfg: DatasetConfig,
    source: Path,
    dest: Path,
    *,
    keep_csv: bool,
    protected: set[str] | None = None,
) -> None:
    """Copy the planned package from *source* to *dest*.

    Stages only the planned artifacts (never a blanket copy): converted
    Parquet mirror paths, non-converted / recursive trees, original CSVs at
    their remote paths when *keep_csv* is ``True`` (PUB-07 — hf target only),
    remotes not skipped by overwrite protection (PUB-05), and any codebooks.

    Args:
        cfg:       Dataset configuration.
        source:    Prepared package directory (mirror layout root).
        dest:      Destination directory (staging root or local ``--output``).
        keep_csv:  When ``True``, also copy original CSVs for converted
                   entries at their remote paths.
        protected: Lowercased remote names skipped by overwrite protection
                   (``None`` = nothing skipped).
    """
    skip = protected or set()
    # Shared expanded set (PUB-10) so copy set == diff set (PUB-09)
    if source.is_dir():
        planned = expanded_planned_remotes(cfg, keep_csv, source)
    else:
        planned = planned_remotes(cfg, keep_csv)

    from pathlib import PurePosixPath as _PP  # noqa: N814

    staged: set[str] = set()
    for remote in planned:
        if remote.lower() in skip or remote.lower() in staged:
            continue
        src = source / _PP(remote)
        if src.exists():
            copy_to_mirror(src, dest, remote)
            staged.add(remote.lower())
        else:
            # Fallback for keep_csv CSV original not in mirror (copied from local)
            # Only for CSV entries where the remote is the verbatim entry.remote
            base = cfg._base_dir if cfg._base_dir else Path.cwd()
            for entry in cfg.files:
                if entry.remote == remote:
                    local = entry.resolve(base)
                    if local.exists():
                        copy_to_mirror(local, dest, remote)
                        staged.add(remote.lower())
                    break

    if "readme.md" not in skip:
        src = source / "README.md"
        if src.exists():
            copy_to_mirror(src, dest, "README.md")
    if "license" not in skip:
        src = source / "LICENSE"
        if src.exists():
            copy_to_mirror(src, dest, "LICENSE")

    codebooks_dir = source / config.CODEBOOKS_DIR
    if codebooks_dir.is_dir():
        for cb in sorted(codebooks_dir.rglob("*.md")):
            copy_to_mirror(cb, dest, cb.relative_to(source).as_posix())
    if (source / "codebook.md").is_file():
        copy_to_mirror(source / "codebook.md", dest, "codebook.md")


def _print_local_package_summary(cfg: DatasetConfig, source: Path) -> None:
    """Print an in-place package summary without mutating anything (PUB-02).

    When ``--target local`` is used without ``--output``, the package is
    already assembled in the build directory — this reports what is there
    and does not copy.

    Args:
        cfg:    Dataset configuration.
        source: Prepared package directory (mirror layout root).
    """
    parquet_count = len(list(source.rglob("*.parquet")))
    codebooks = _collect_codebook_remotes(source)
    print("\n  Local target: package is already assembled in place:")
    print(f"    {source}")
    print(f"    Parquet files: {parquet_count}")
    print(f"    README.md: {'yes' if (source / 'README.md').is_file() else 'no'}")
    print(f"    LICENSE: {'yes' if (source / 'LICENSE').is_file() else 'no'}")
    print(f"    Codebooks: {len(codebooks)}")
    print()


def publish(
    cfg: DatasetConfig,
    target: str = "hf",
    output_dir: str | None = None,
    force: bool = False,
    verify: bool = False,
    keep_csv: bool = False,
    dry_run: bool = False,
    quality_report: ValidationReport | None = None,
    protected_out: set[str] | None = None,
    clean: bool = False,
    clean_cache: bool = False,
    token: str | None = None,
) -> int:
    """Deliver the prepared dataset package for *cfg* to *target*.

    Full flow — see the module docstring for the orchestration walk-through.

    Args:
        cfg:           Dataset configuration.
        target:        Delivery target: ``"hf"`` (Hugging Face Hub, default)
                       or ``"local"`` (copy to ``--output``).
        output_dir:    ``hf``: override the prepare output directory
                       (default ``[dataset] build_dir``).  ``local``:
                       destination directory for the package copy.
        force:         When ``True``, skip overwrite protection on the hf
                       target.
        verify:        Accepted for signature compatibility; verification
                       belongs to ``prepare`` (``prepare --verify``) and is
                       never re-run after delivery.
        keep_csv:      When ``True`` and a CSV was converted to Parquet, also
                       deliver the original CSV at its remote path (hf
                       target only — PUB-07).
        dry_run:       When ``True``, print the diff and split report from the
                       planned remotes only; never prepares, copies, or
                       touches the network (PUB-04).
        quality_report: Optional pre-computed quality validation report.
                        When provided and failing, hf delivery is blocked
                        before any network call (PUB-01).
        protected_out: Optional out-param (adv8): when given, the set of
                       lowercased remote names skipped by overwrite
                       protection (computed at :func:`_check_overwrite_protection`)
                       is written into it, so callers can surface
                       ``skipped_protected`` without re-inspecting the repo
                       or parsing output.  ``None`` keeps the legacy behavior
                       (no side channel).
        clean:         When ``True``, delete the build directory after a
                       successful ``hf`` upload (PUB-11) or the ``local``
                       destination after a successful copy.  Default off;
                       never deletes on ``--dry-run``, quality-gate block,
                       or upload failure.  Build path is resolved via
                       :func:`sofer.prepare.resolve_output_dir` so
                       ``--output`` overrides are honoured.
        clean_cache:   When ``True`` and *clean* is also ``True``, also
                        delete ``cache/`` (``config.OUTPUT_DIR`` anchored to
                        ``cfg._base_dir``, shared tool-wide).  Requires
                        explicit opt-in via ``--clean-cache``/``--all`` (PUB-11).
        token:       Optional HF token; when given ``HfApi(token=token)`` is
                     used, otherwise the module-level ``_api`` (no implicit
                     token). The token is never logged.

    Returns:
        Exit code (``0`` success, ``1`` quality-gate failure, prepare
        failure, or hf upload failure).
    """
    # For the hf target this is the prepare-output / staging source; for the
    # local target it is the *destination* of the package copy.
    source = resolve_output_dir(cfg, output_dir if target == "hf" else None)

    print(f"\n{'=' * 60}")
    print(f"  Dataset:   {cfg.name}")
    print(f"  Target:    {target}")
    print(f"  Output:    {source}")
    print(f"  File entries: {len(cfg.files)}")
    print(f"{'=' * 60}\n")

    # Ensure UTF-8 output for Unicode characters on Windows.
    if sys.platform == "win32" and hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")

    # ── 1. Auto-prepare (PUB-03) — never under --dry-run (PUB-04) ────────
    # all_files=True: the delivered package must include codebooks even when
    # the user never ran `prepare --all-files` themselves.
    if not dry_run and _needs_prepare(cfg, source):
        print("  [i] Output is stale or missing - running prepare first ...")
        rc = prepare(cfg, source, force=True, all_files=True)
        if rc != 0:
            return rc

    # Shared expanded set (PUB-10) — ground truth when mirror exists else placeholder
    if source.is_dir():
        planned = expanded_planned_remotes(cfg, keep_csv, source)
    else:
        planned = planned_remotes(cfg, keep_csv)

    # ── 2. Dry-run: diff + split report, no network, no mutation ─────────
    if dry_run:
        codebook_remotes = _collect_codebook_remotes(source) if source.is_dir() else []
        diff = _repo_diff_summary(cfg, [], keep_csv, codebook_remotes, staging_dir=source)
        print(diff)
        print()
        _print_split_mapping_validation(planned)
        report = detect_splits(planned)
        _print_split_report(report)
        print(f"\n{'=' * 60}")
        print("  Dry-run complete - no files uploaded.")
        print(f"{'=' * 60}\n")
        return 0

    # ── 3. Local target: copy to --output or in-place summary (PUB-02) ───
    if target == "local":
        if output_dir is None:
            _print_local_package_summary(cfg, source)
            return 0
        dest = resolve_output_dir(cfg, output_dir)
        print(f"  [i] Copying package from {source} to {dest} ...")
        # --keep-csv has no effect on the local target (PUB-07).
        _copy_package(cfg, source, dest, keep_csv=False)
        print(f"\n{'=' * 60}")
        print(f"  Result: package copied to {dest}")
        print(f"{'=' * 60}\n")
        # PUB-11: local --clean deletes the resolved destination only,
        # never the source build.  Without --clean, nothing is deleted.
        if clean and not dry_run:
            # quality gate applies to hf only; local always has quality_passed
            from ._clean import clean_build as _clean_build_local

            # clean_build expects a DatasetConfig + override string; for local
            # we clean the destination resolved from the --output string.
            _clean_build_local(cfg, output_dir)
        return 0

    # ── 4. hf target: quality gate, repo, diff, protection (PUB-01) ──────
    if quality_report is not None and not quality_report.passed:
        print("\n  \u26a0  Quality checks failed - fix errors before publishing.\n")
        quality_report.print_summary()
        return 1

    api = HfApi(token=token) if token is not None else None
    # Fail-closed remote prologue (PUB-05): a create_repo failure or an
    # inspection failure (anything but repo-not-found) aborts the publish
    # with rc 1 BEFORE any staging/upload — remote state is unknown, so
    # overwrite protection cannot be trusted and proceeding could overwrite
    # protected remotes. Inspection failure is NEVER treated as an empty repo.
    try:
        _ensure_repo(cfg, api=api)
        existing_files = _inspect_repo(cfg, api=api)
    except Exception as exc:
        print(f"\n  \u2717  Remote inspection failed: {exc}")
        print("  Publish aborted — remote state unknown, refusing to upload (fail closed).")
        return 1

    codebook_remotes = _collect_codebook_remotes(source)

    # ── PUB-08: warn (never block) when the package carries no codebooks ─
    # A fresh bare-`prepare` build is up-to-date, so auto-prepare skipped and
    # nothing regenerated the codebooks; advise, then deliver anyway.
    if not codebook_remotes:
        print(
            "  [!] No codebooks found in this package - it will be delivered without them.\n"
            "     Run `sofer prepare --all-files` to generate per-file codebooks first."
        )

    diff = _repo_diff_summary(cfg, existing_files, keep_csv, codebook_remotes, staging_dir=source)
    print(diff)
    print()

    protected = _check_overwrite_protection(existing_files, force, planned_files=planned)
    if protected_out is not None:
        protected_out.update(protected)
    _print_split_mapping_validation(planned)

    # ── 5. Staging + single upload_folder call ───────────────────────────
    tmpdir = Path(tempfile.mkdtemp())
    try:
        staging_root = tmpdir / "repo"
        staging_root.mkdir()
        _copy_package(cfg, source, staging_root, keep_csv=keep_csv, protected=protected)

        # Report NOT FOUND declared sources (advisory, never uploaded).
        base = cfg._base_dir if cfg._base_dir else Path.cwd()
        for entry in cfg.files:
            local = entry.resolve(base)
            if not local.exists():
                print(f"  \u2717  NOT FOUND: {local}")

        staged_count = sum(1 for _ in staging_root.rglob("*") if _.is_file())
        # _hf_upload_folder never raises: it catches and prints the error
        # internally and returns ``False`` on failure (its documented
        # contract, see :func:`_hf_upload_folder`). Account on that return
        # value — a falsy result means the single upload_folder call
        # delivered nothing, so every staged file counts as failed (rc 1).
        # The try/except that previously wrapped this call was dead code
        # and masked total upload failures as success (ok=staged_count,
        # fail=0 → rc 0).
        if _hf_upload_folder(cfg.repo_id, staging_root, "", cfg.repo_type, api=api):
            ok = staged_count
            fail = 0
        else:
            ok = 0
            fail = staged_count or 1
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)

    # ── 6. Post-upload split report ──────────────────────────────────────
    # The upload already succeeded; a post-upload inspection failure warns
    # and skips the split report — it never fails the completed upload.
    try:
        updated_files = _inspect_repo(cfg, api=api)
    except Exception as exc:
        print(f"  \u26a0  Post-upload inspection failed: {exc}")
        print("     Upload completed; the split report is skipped.")
        updated_files = []
    if updated_files:
        report = detect_splits(updated_files)
        _print_split_report(report)

    print(f"\n{'=' * 60}")
    print(f"  Result: {ok} uploaded, {fail} failed")
    print(f"{'=' * 60}\n")

    # ── 7. PUB-11 gated cleanup: --clean deletes build only on success ──
    # Gated on clean && not dry_run && quality_passed && fail==0.  Build is
    # resolved via resolve_output_dir(cfg, output_dir) so --output overrides
    # are honoured; cache is tool-wide at cfg._base_dir / config.OUTPUT_DIR
    # and requires explicit --clean-cache/--all (sibling-shared).
    quality_passed = quality_report is None or quality_report.passed
    if clean and not dry_run and quality_passed and fail == 0:
        from ._clean import clean_build as _clean_build_hf
        from ._clean import clean_cache as _clean_cache_hf

        # output_dir here is the original string override (None = cfg.build_dir)
        _clean_build_hf(cfg, output_dir)
        if clean_cache:
            base = cfg._base_dir if cfg._base_dir else Path.cwd()
            _clean_cache_hf(base)

    return 0 if fail == 0 else 1
