"""
End-to-end ``datasets.load_dataset()`` verification for staged datasets.

Verifies that a dataset generated by this tool actually loads correctly
with the Hugging Face ``datasets`` library — the canonical test that a
user calling ``load_dataset("user/repo")`` will succeed.

The ``datasets`` package is an *optional* dependency: when it is not
installed, verification is skipped with an informational message rather
than failing the upload.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from .model import DatasetConfig
from .splits import detect_splits


@dataclass
class VerificationReport:
    """Result of a :func:`verify_load_dataset` run.

    Attributes:
        passed:            ``True`` when ``load_dataset()`` succeeded and
                           splits matched expectations.
        skipped:           ``True`` when ``datasets`` was not available.
        split_names:       Actual split names returned by ``load_dataset()``.
        split_row_counts:  Row counts per split.
        expected_splits:   Split names we expected based on remote-path detection.
        warnings:          Non-fatal issues (e.g. minor mismatches).
        errors:            Fatal issues (e.g. ``load_dataset()`` raised).
    """

    passed: bool = False
    skipped: bool = False
    split_names: list[str] = field(default_factory=list)
    split_row_counts: dict[str, int] = field(default_factory=dict)
    expected_splits: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)


def verify_load_dataset(
    staging_dir: Path,
    cfg: DatasetConfig,
) -> VerificationReport:
    """Verify a staged dataset loads correctly with ``datasets.load_dataset()``.

    Performs an end-to-end load of the *staging_dir* contents and compares
    the detected splits against the split mapping declared (or implied) by
    the dataset configuration.

    Args:
        staging_dir:  Directory containing the staged data files (Parquet / CSV)
                      plus compliance files (README.md, LICENSE).
        cfg:          The dataset configuration used to generate this staging.

    Returns:
        A :class:`VerificationReport` with the results.
    """
    # ── Optional dependency guard ────────────────────────────────────────
    try:
        import datasets
    except ImportError:
        return VerificationReport(
            passed=False,
            skipped=True,
            warnings=[
                "`datasets` package is not installed — skipping load_dataset() "
                "verification. Install with: pip install datasets"
            ],
        )

    # ── Build expected splits from remote paths ──────────────────────────
    remotes = [e.remote for e in cfg.files if not e.recursive]
    expected_report = detect_splits(remotes)
    expected_names = [s.name for s in expected_report.splits]

    # ── Perform the load ─────────────────────────────────────────────────
    errors: list[str] = []
    warnings: list[str] = []

    try:
        ds = datasets.load_dataset(str(staging_dir))
    except Exception as exc:
        return VerificationReport(
            passed=False,
            skipped=False,
            expected_splits=expected_names,
            errors=[f"load_dataset() raised: {exc}"],
        )

    # ── Inspect splits ───────────────────────────────────────────────────
    actual_splits = [str(name) for name in ds.keys()]
    split_row_counts: dict[str, int] = {}
    for name in actual_splits:
        try:
            split_row_counts[name] = len(ds[name])
        except Exception:
            split_row_counts[name] = -1  # unable to determine

    # ── Compare against expectations ─────────────────────────────────────
    if set(actual_splits) != set(expected_names):
        warnings.append(
            f"Split names differ from expected: got {actual_splits}, expected {expected_names}"
        )

    passed = len(errors) == 0 and len(warnings) == 0

    return VerificationReport(
        passed=passed,
        skipped=False,
        split_names=actual_splits,
        split_row_counts=split_row_counts,
        expected_splits=expected_names,
        warnings=warnings,
        errors=errors,
    )


def _print_verification_report(report: VerificationReport) -> None:
    """Print a human-readable verification summary to stdout."""
    if report.skipped:
        print("\n  [i] load_dataset() verification: SKIPPED")
        for w in report.warnings:
            print(f"      {w}")
        return

    status = "\u2713  PASSED" if report.passed else "\u2717  FAILED"
    print(f"\n  load_dataset() verification: {status}")

    if report.errors:
        for e in report.errors:
            print(f"      Error: {e}")

    if report.split_names:
        print(f"      Splits: {', '.join(report.split_names)}")
        for name, count in report.split_row_counts.items():
            count_str = str(count) if count >= 0 else "?"
            print(f"        [{name}] {count_str} rows")

    if report.expected_splits and report.split_names != report.expected_splits:
        print(f"      Expected: {', '.join(report.expected_splits)}")

    if report.warnings:
        for w in report.warnings:
            print(f"      Warning: {w}")
