"""
Automatic codebook generation from CSV files.

A *codebook* documents every column in a dataset: name, inferred type,
unique values, missing percentage, and a sample value.  This follows the
data-sharing standard recommended by the `Leek group guide`_.

.. _Leek group guide: https://github.com/jtleek/datasharing

The implementation is intentionally domain-agnostic — it works for
census data, surveys, shapes, or any tabular data.
"""

from __future__ import annotations

import csv
from pathlib import Path


def infer_column_type(values: list[str]) -> str:
    """Guess the semantic type of a column from a sample of its values.

    Returns one of ``"numeric"``, ``"categorical/text"``,
    ``"mixed (mostly numeric)"``, or ``"unknown"``.
    """
    numeric_count = 0
    total = len(values)
    for v in values:
        cleaned = v.strip()
        if not cleaned or cleaned.upper() in (
            "NA",
            "N/A",
            "NOTAPPLICABLE",
            "MISSING",
            "NULL",
        ):
            continue
        try:
            float(cleaned.replace(",", "."))
            numeric_count += 1
        except ValueError:
            pass
    if numeric_count == 0:
        return "categorical/text"
    if total == 0:
        return "unknown"
    ratio = numeric_count / total
    if ratio > 0.9:
        return "numeric"
    if ratio > 0.5:
        return "mixed (mostly numeric)"
    return "categorical/text"


# Backward-compat alias (will be removed in a future version)
_infer_type = infer_column_type


def generate(
    csv_path: str,
    output_path: str | None = None,
    delimiter: str = ";",
    encoding: str = "utf-8-sig",
    max_sample: int = 100_000,
) -> str:
    """Generate a markdown codebook from a CSV file.

    The codebook analyses up to *max_sample* rows to infer column types,
    unique value counts, and missing-data proportions.

    Args:
        csv_path:   Path to the input CSV.
        output_path: If given, write the codebook to this file.
        delimiter:  CSV delimiter character (default ``;``).
        encoding:   File encoding (default ``utf-8-sig`` for Excel compat).
        max_sample: Maximum rows to read for analysis.

    Returns:
        The codebook as a markdown string.
    """
    path = Path(csv_path)
    with open(path, newline="", encoding=encoding) as fh:
        reader = csv.reader(fh, delimiter=delimiter)
        headers = next(reader)
        rows = list(reader)

    total_rows = len(rows)
    sample = rows[: min(total_rows, max_sample)]

    lines = [
        f"# Codebook: {path.name}",
        "",
        f"**File:** `{path.name}`",
        f"**Rows:** {total_rows:,}",
        f"**Columns:** {len(headers)}",
        f"**Analysed rows:** {min(total_rows, max_sample):,} "
        f"({'full scan' if total_rows <= max_sample else 'sample'})",
        "",
        "| # | Column | Type | Unique | Missing (%) | Example |",
        "|---|--------|------|--------|-------------|---------|",
    ]

    for idx, col in enumerate(headers, 1):
        col_values = [row[idx - 1] if idx - 1 < len(row) else "" for row in sample]
        n_unique = len(set(col_values))
        n_missing = sum(
            1
            for v in col_values
            if not v.strip() or v.strip().upper() in ("NA", "N/A", "NOTAPPLICABLE", "MISSING")
        )
        pct_missing = round(n_missing / len(sample) * 100, 1) if sample else 0.0
        col_type = infer_column_type(col_values)
        example = next(
            (v for v in col_values if v.strip() and v.strip().upper() not in ("NA", "")),
            "",
        )
        lines.append(
            f"| {idx} | `{col}` | {col_type} | {n_unique} | {pct_missing}% | `{example}` |"
        )

    lines.extend(["", "", "_Generated by data-uploader_"])
    codebook = "\n".join(lines)

    if output_path:
        Path(output_path).write_text(codebook, encoding="utf-8")

    return codebook
